//
// Created by Luiz Veloso on 13/04/22.
//

#ifndef BROKERAPP_ORDERLOGTABLEDELEGATE_H
#define BROKERAPP_ORDERLOGTABLEDELEGATE_H


class OrderLogTableDelegate {

};


#endif //BROKERAPP_ORDERLOGTABLEDELEGATE_H
